package com.checkspace.backend.dto.request;

import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.math.BigDecimal;

@Data
public class CreateOrderRequest {

    @NotNull
    private Long userId;

    private Long propertyId; // null for verification fee, set for token amount

    @NotNull
    private BigDecimal amount;

    @NotNull
    private String paymentType; // VERIFICATION_FEE or TOKEN_AMOUNT

    @NotNull
    private String idempotencyKey; // generated by frontend
}